<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');

?>
<div class="product-img-box">

<?php if (count($this->getGalleryImages()) > 0): ?>
<ul id="etalage1" class="cloud_zoom">
<?php foreach ($this->getGalleryImages() as $_image): ?>
    <li class="zoom_img">
        <?php
            $image_src = $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(700, 700);
        ?>        
        <img class="zoom_img_image" src="<?php echo $image_src; ?>">
        <img class="zoom_source_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(100, 100)?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
        <span class="roll-over"><?php echo $this->__('Roll over image to zoom in') ?></span>
    </li>
<?php endforeach; ?>
</ul>
<?php else: ?>
<ul id="etalage1" class="cloud_zoom">
    <li class="zoom_img">
        <?php
            $image_src = $this->helper('catalog/image')->init($_product, 'image')->resize(700, 700);
        ?>        
        <img class="zoom_img_image" src="<?php echo $image_src; ?>">
        <img class="zoom_source_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(100, 100)?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()) ?>">
        <span class="roll-over"><?php echo $this->__('Roll over image to zoom in') ?></span>
    </li>
</ul>
<?php endif; ?>

<div class="zoom-control"> <a href="javascript:void(0)" class="zoom-prev"><?php echo $this->__('Previous') ?></a> <a href="javascript:void(0)" class="zoom-next"><?php echo $this->__('Next') ?></a> </div>

<script type="text/javascript">
    jQuery(document).ready(function(){
        var width = jQuery('.product-view .product-img-box').width() * 0.80;
        var src_img_width = 60;
        var src_img_height = 85;
        var ratio_width = 400;
        var ratio_height = 400;
        
        src_img_width = 100 * ratio_width / ratio_height;
        var height = width * ratio_height / ratio_width;

        jQuery('#etalage1').cloud_zoom({
            thumb_image_width: width,
            thumb_image_height: height,
            source_image_width: src_img_width,
            source_image_height: src_img_height,
            zoom_area_width: width,
            zoom_area_height: height,
            zoom_enable: false,
            smallthumb_hide_single: false,
            smallthumbs_position: 'right',
            show_icon: false,
            autoplay: false
        });
        jQuery(".product-img-box .cloud_zoom li.zoom_img").zoom();
        jQuery('.product-view .product-img-box .zoom-control a').css('right',((jQuery('.zoom_small_thumbs img').first().width())/2-3)+"px");
        if(jQuery('.zoom_small_thumbs').width() == 0)
            jQuery('.product-view .product-img-box .zoom-control a').css('right',((jQuery('.zoom_small_thumbs img').first().width())/2-3)+"px");
        jQuery(window).resize(function(e){
            var width = jQuery('.product-view .product-img-box').width() * 0.80;
            var height = width * ratio_height / ratio_width;
            zoom_enabled = false;
            if(jQuery(window).width()<500)
                zoom_enabled = false;
            jQuery('#etalage1').cloud_zoom({
                thumb_image_width: width,
                thumb_image_height: height,
                source_image_width: src_img_width,
                source_image_height: src_img_height,
                zoom_area_width: width,
                zoom_area_height: height,
                zoom_enable: zoom_enabled,
                smallthumb_hide_single: false,
                smallthumbs_position: 'right',
                show_icon: true,
                autoplay: false
            });
            jQuery('.product-view .product-img-box .zoom-control a').css('right',((jQuery('.zoom_small_thumbs').width())/2)+"px");
        });
        jQuery('.zoom-prev').on('click', function(){
            etalage1_previous();
        });

        jQuery('.zoom-next').on('click', function(){
            etalage1_next();
        });
    });
</script>

 </div> <!--product-img-box--> 

