<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product);
?>


<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/cloud-zoom.js') ?>"></script>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="product-view">
    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="magik_quickview"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
    <div class="product-essential">
	
	  <?php echo $this->getChildHtml('media') ?>
	  <div class="product-shop">
	      <div class="product-name">
		  <h1>
		      <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
		      <?php echo $this->htmlEscape($_product->getName()); ?> </a>
                  </h1>  
	      </div> <!--product-name-->

              <?php echo $this->getReviewsSummaryHtml($_product, 'aggregate', true)?>

               <?php if ($_product->isAvailable()): ?>
                  <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
               <?php else: ?>
                  <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
               <?php endif; ?> 

               <?php echo $this->getChildHtml('product_type_data') ?>
               <?php echo $this->getChildHtml('bundle_prices') ?>
               <?php echo $this->getTierPriceHtml() ?>
               <?php echo $this->getChildHtml('extrahint') ?>

              <div class="short-description">
                 <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
              </div>

            <?php if($_product->isSaleable()): ?>
                      <?php if($this->hasOptions()): ?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                     <?php endif; ?>
            <?php endif; ?>

             <div class="add-to-box">
              <div class="add-to-cart">
               <div class="pull-left">
               <?php if($_product->isSaleable()): ?>
                <?php if(!$_product->isGrouped()): ?>
                  <div class="pull-left">
                    <label for="qty"><?php echo $this->__('Quantity') ?></label>                    
                    <input type="text" name="qty" id="qty1"  maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Quantity:') ?>" class="input-text qty" />
                  </div> <!--pull-left-->
                  <div class="custom pull-left">
                    <button onClick="var result = document.getElementById('qty1'); var qty1 = result.value; if( !isNaN( qty1 )) result.value++;return false;" class="increase items-count" type="button"><i class="icon-angle-up">&nbsp;</i></button>
                    <button onClick="var result = document.getElementById('qty1'); var qty1 = result.value; if( !isNaN( qty1 ) &amp;&amp; qty1 &gt; 0 ) result.value--;return false;" class="reduced items-count" type="button"><i class="icon-angle-down">&nbsp;</i></button>
                  </div> <!--custom pull-left-->
                <?php endif; ?>
                   <button title="<?php echo $this->__('Add to Cart') ?>" type="button" class="button btn-cart"  onclick="productAddToCartForm.submit(this)"><span><?php echo $this->__('Add to Cart')?></span></button>
                <?php else: ?>
                      <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                </div> <!--pull-left-->
               </div> <!--add-to-cart-->
              </div> <!--add-to-box-->
	     	     
	</div> <!--product-shop-->
  </div> <!--product-essential-->
</form>
<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('magik_quickview');
        productAddToCartForm.submit = function(button, url) { 
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){ 
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
</div> <!--product-view-->

