<?php
              // some helpers
              $_helper = $this->helper('catalog/output');
              $storeId = Mage::app()->getStore()->getId();
              $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
              $productCount = $this->getData('num_products');

$visibility = array( 
                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH, 
                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                );
$attributeInfo = Mage::getResourceModel('eav/entity_attribute_collection')
              ->setCodeFilter('magikfeatured')
              ->getFirstItem();
  $attribute_info = $attributeInfo->getData();
 
  if($attribute_info['attribute_code'] == 'magikfeatured'){
$collection = Mage::getResourceModel('reports/product_collection') 
                      ->addAttributeToSelect('*')     
                      ->setStoreId($storeId) 
                      ->addStoreFilter($storeId)     
                      ->addAttributeToFilter('visibility', $visibility)
                      ->addAttributeToFilter('magikfeatured', true) 
                      ->setOrder('updated_at', 'desc')
                      ->addAttributeToSelect('status') 
                      ->setPageSize($productCount);
                       Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
                       Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);
$collection->joinField('is_in_stock','cataloginventory/stock_item','is_in_stock','product_id=entity_id')->addAttributeToFilter('is_in_stock', 1);

/*  To display product by category id */
if($categoryId=$this->getData('category_id')){
      $category = Mage::getModel('catalog/category')->load($categoryId);
      $collection->addCategoryFilter($category);
    } ?>

<div class="pdt-content pdt_featured_pr is-loaded">
  <div class="pdt-list products-grid-home zoomOut">

<?php
// if no products are currently featured, display some text
   if (!$collection->count()) :
?>
    <p class="note-msg"><?php echo $this->__('There are no featured products at the moment.') ?></p>
      
<?php else : ?>

      
        <?php
                $_collectionSize = $collection->count();
                $_columnCount = 4;
                $i = 0;
                
                foreach ($collection as $_product) :
                        $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
        ?>
            <?php if ($i++%$_columnCount==0): ?>
            
            <?php endif ?>

                <div class="item item-animate wide-<?php if(($i-1)%$_columnCount==0): ?>first<?php elseif($i%$_columnCount==0): ?>last<?php endif; ?>"> 
                 <div class="item-inner">
                   <div class="item-img">
                     <div class="item-img-info">
                       <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(265,265); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />                    
                       </a>
                      <?php echo $this->helper('civicsettings')->getLabel($_product);  ?>
                      <div class="item-box-hover">
                          <div class="box-inner">
                            <span class="add-to-links">
                               <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                 <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"></a>
                               <?php endif; ?>
                               <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                 <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to compare');?>"></a>
                               <?php endif; ?> 
                            </span> <!--add-to-links-->
                            <?php if(Mage::app()->getStore()->getConfig('civicsettings/civicsettings_quickview/enable')==1){?> 
                             <div class="product-detail-bnt">
                               <a data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('civicsettings/index/view/id/'.$_product->getId());?>');" title="<?php echo $this->__('Quick View') ?>" class="button detail-bnt"><span><?php echo $this->__('Quick View') ?></span></a>
                             </div> <!--product-detail-bnt-->
                            <?php } ?> 
                          </div> <!--box-inner-->
                       </div> <!--item-box-hover-->
                     </div> <!--item-img-info-->
                   </div> <!--item-img-->

                  <div class="item-info">
                    <div class="info-inner">
                       <div class="item-title">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                           <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                           if(strlen($prod_name) > 20) {echo substr($prod_name,0,20)."...";}else {echo $prod_name;}?>
                        </a>
                       </div> <!--item-title-->
                       <div class="item-content">
                    <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="ratings"><div class="no-rating-box-blank"><div class="no-rating-box"></div></div></div>
                    <?php } ?>
                          <div class="item-price">
                             <?php echo $this->getPriceHtml($_product, true) ?>
                          </div> <!--item-price-->
                       </div> <!--item-content-->
                    </div> <!--info-inner-->

                     <div class="actions">
                          <?php if($_product->isSaleable()): ?>
                             <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                          <?php else: ?>
                             <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                          <?php endif; ?>
                     </div> <!--actions-->

                  </div> <!--item-info-->
                 </div> <!--item-inner-->                               
                </div> <!-- item -->

            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            
            <?php endif ?>
            
                <?php endforeach ?>

      <?php endif ?>  <!--Endif !$collection->count() -->
  </div> <!--pdt-list products-grid-home zoomOut-->
</div> <!--pdt-content pdt_featured_pr is-loaded-->
<?php } ?> <!-- chk attribute_code -->

<div id="mgkquickview2">
<div id="magikloading2" style="display:none;text-align:center;margin-top:400px;"><img src="<?php echo $this->getSkinUrl('images/mgkloading.gif');?>" alt="loading">
</div></div>
<script type="text/javascript">
function callQuickView(qurl) { 
    jQuery('#mgkquickview2').show();
    jQuery('#magikloading2').show();
    jQuery.get(qurl, function(data) {
      jQuery.fancybox(data);
      jQuery('#magikloading2').hide();
jQuery('#mgkquickview2').hide();
    });
 }
 
</script>

