<?php if (Mage::getStoreConfig('civicsettings/civicsettings_products/related_product')): ?>

<?php if($this->getItems()->getSize()): ?>

<?php  $_helper = $this->helper('catalog/output'); ?>

<div class="related-block">
  <div class="block-title"> 
     <h2><span><?php echo $this->__('Related Products') ?></span></h2>
  </div> <!--block-title-->

<div class="block-content category-products">

<div class="jcarousel-skin-tango4">
    <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;">
      <div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;">
        <ul class="products-grid jcarousel-list jcarousel-list-horizontal" id="mycarousel4" style="overflow: hidden; position: relative; top: 0px; margin: 0px; padding: 0px; left: 0px; width: 2507px;">

       <?php foreach($this->getItems() as $_item): ?>
            <li class="item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal">
              <div class="item-inner">
                 <div class="item-img">
                    <div class="item-img-info">
                       <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image">
                         <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(265,265) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
                       </a>                       
                    <div class="item-box-hover">
                       <div class="box-inner">
                         <span class="add-to-links">
                           <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>" class="link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"></a>
                           <?php endif; ?>                        
                           <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                            <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to compare');?>"></a>
                           <?php endif; ?>
                         </span> <!--add-to-links-->
                         <?php if(Mage::app()->getStore()->getConfig('civicsettings/civicsettings_quickview/enable')==1){?>
                          <div class="product-detail-bnt">
                              <a data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('civicsettings/index/view/id/'.$_item->getId());?>');" title="<?php echo $this->__('Quick View') ?>" class="button detail-bnt"><span><?php echo $this->__('Quick View') ?></span></a>                    
                          </div> <!--product-detail-bnt-->
                         <?php } ?>
                       </div> <!--box-inner-->
                    </div> <!--item-box-hover-->

                    </div> <!--item-img-info-->
                 </div> <!--item-img-->
                 <div class="item-info">
                   <div class="info-inner">
                    <div class="item-title">
                        <a class="product-name" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                          <?php $prod_name = $this->htmlEscape($_item->getName()) ; 
                           if(strlen($prod_name) > 20) {echo substr($prod_name,0,20)."...";}else {echo $prod_name;}?>
                        </a>
                    </div> <!--item-title-->
                    <div class="item-content">
                    <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_item->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="no-rating-box-blank"><div class="no-rating-box"></div></div>
                    <?php } ?>
                       <div class="item-price">
                          <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                       </div> <!--item-price-->
                    </div> <!--item-content-->
                   </div> <!--info-inner-->
                  <div class="actions">
                        <?php if($_item->isSaleable()): ?>
                          <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                        <?php else: ?>
                          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                  </div> <!--actions-->

                 </div> <!--item-info-->
              </div> <!--item-inner-->             
            </li>
             <?php endforeach; ?>  
        
         
        <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
  
          </ul>
       </div> <!--jcarousel-clip jcarousel-clip-horizontal-->

      <div class="jcarousel-prev jcarousel-prev-horizontal" style="display: block;"></div>
      <div class="jcarousel-next jcarousel-next-horizontal" style="display: block;"></div>

     </div> <!--jcarousel-container jcarousel-container-horizontal-->
</div> <!-- jcarousel-skin-tango4-->

  </div> <!--block-content category-products-->
</div> <!--related-block-->

<?php endif; ?>  <!-- end related product -->

<?php endif; ?>

<div id="mgkquickview">
<div id="magikloading" style="display:none;text-align:center;margin-top:400px;"><img src="<?php echo $this->getSkinUrl('images/mgkloading.gif');?>" alt="loading">
</div></div>
<script type="text/javascript">
function callQuickView(qurl) { 
    jQuery('#mgkquickview').show();
    jQuery('#magikloading').show();
    jQuery.get(qurl, function(data) {
      jQuery.fancybox(data);
      jQuery('#magikloading').hide();
jQuery('#mgkquickview').hide();
    });
 }
 
</script>