
<?php if (Mage::getStoreConfig('civicsettings/civicsettings_products/upsell_product')): ?>

<?php if(count($this->getItemCollection()->getItems())): ?>

<?php $_helper = $this->helper('catalog/output'); ?>

<div class="category-products">

  <div id="upsell-product-table">      
    <?php $this->setColumnCount(4); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

        <ul class="products-grid first odd">
  <?php $_iterator = 0; ?>      
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>

        <?php if ($_iterator++%$_columnCount==0): ?>

        <?php endif ?>
<?php //if($_iterator > 4) { ?>
 <li class="item<?php if(($_iterator-1)%$_columnCount==0): ?> first<?php elseif($_iterator%$_columnCount==0): ?> last<?php endif; ?>">

               <div class="item-inner">
                 <div class="item-img">
                    <div class="item-img-info">
                       <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                         <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(265,265) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
                       </a>
                    <div class="item-box-hover">
                       <div class="box-inner">
                        <span class="add-to-links">
                           <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_link) ?>" class="link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"></a>
                           <?php endif; ?>
                           <?php if($_compareUrl=$this->getAddToCompareUrl($_link)): ?>
                            <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to compare');?>"></a>
                           <?php endif; ?>
                        </span> <!--add-to-links-->
                        <?php if(Mage::app()->getStore()->getConfig('civicsettings/civicsettings_quickview/enable')==1){?>
                          <div class="product-detail-bnt">
                              <a data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('civicsettings/index/view/id/'.$_link->getId());?>');" title="<?php echo $this->__('Quick View') ?>" class="button detail-bnt"><span><?php echo $this->__('Quick View') ?></span></a>                    
                          </div> <!--product-detail-bnt-->
                        <?php } ?>
                       </div> <!--box-inner-->
                    </div> <!--item-box-hover-->
                    </div> <!--item-img-info-->
                 </div> <!--item-img-->

                 <div class="item-info">
                   <div class="info-inner">
                    <div class="item-title">
                        <a class="product-name" href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($_link->getName(), null, true) ?>">
                          <?php $prod_name = $this->htmlEscape($_link->getName()) ; 
                           if(strlen($prod_name) > 20) {echo substr($prod_name,0,20)."...";}else {echo $prod_name;}?>
                        </a>
                    </div> <!--item-title-->
                    <div class="item-content">
                    <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_link->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="no-rating-box-blank"><div class="no-rating-box"></div></div>
                    <?php } ?>
                       <div class="item-price">
                          <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                       </div> <!--item-price-->
                    </div> <!--item-content-->
                   </div> <!--info-inner-->

                  <div class="actions">
                        <?php if($_link->isSaleable()): ?>
                          <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                        <?php else: ?>
                          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                  </div> <!--actions-->

                 </div> <!--item-info-->
              </div> <!--item-inner-->                                                                    
            </li>
<?php //} ?>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>

        <?php endif ?>

            <?php else: ?>
            <?php /* <li class="empty">&nbsp;</li> */ ?>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
          </ul>       
  </div>  <!--upsell-product-table-->

</div> <!--category-products-->

<?php endif ?>

<?php endif; ?> 

<script type="text/javascript">decorateTable('upsell-product-table')</script>

<div id="mgkquickview">
<div id="magikloading" style="display:none;text-align:center;margin-top:400px;"><img src="<?php echo $this->getSkinUrl('images/mgkloading.gif');?>" alt="loading">
</div></div>
<script type="text/javascript">
function callQuickView(qurl) { 
    jQuery('#mgkquickview').show();
    jQuery('#magikloading').show();
    jQuery.get(qurl, function(data) {
      jQuery.fancybox(data);
      jQuery('#magikloading').hide();
jQuery('#mgkquickview').hide();
    });
 }
</script>