<div class="ratings" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <?php if ($this->getRatingSummary()):?>
        <meta itemprop="ratingValue" content="<?php echo $this->getRatingSummary(); ?>">
        <meta itemprop="reviewCount" content="<?php echo $this->getReviewsCount(); ?>">
        <meta itemprop="bestRating" content="100">
        <meta itemprop="worstRating" content="0">
        <div class="rating-box">
            <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
        </div>
    <?php endif;?>
    <p class="rating-links">
        <a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
        <span class="separator">|</span>
        <a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Add Your Review') ?></a>
    </p>
</div>