
<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>

<?php if(count($this->getStores())>1): ?>
<!-- BEGIN BLOCK LANGUAGE -->
<div class="language-box">
<!-- BEGIN BLOCK CONTENT DROPDOWN -->
 <div class="language-switcher"> 
   <div class="language_detail" style="display: none;">
     <div class="language-inner">
       <div class="language">
        <p><?php echo $this->__('Change language') ?></p>
        <ul>
        <?php $i=0; foreach ($this->getStores() as $_lang): ?>  
         <li class="item<?php if( ++$i == count($this->getStores()) ): ?> last<?php endif; ?>">     
          <a href="<?php echo $_lang->getCurrentUrl();?>" title="<?php echo $this->htmlEscape($_lang->getName()) ?>">
           <img src="<?php echo $this->getSkinUrl('images/flags/'.$this->htmlEscape($_lang->getCode()).'.png') ?>" alt="<?php echo $this->htmlEscape($_lang->getName()) ?>" />
           <span><?php echo $this->htmlEscape($_lang->getName()) ?></span>
          </a> 
         </li>       
        <?php endforeach; ?>
        </ul>
       </div> <!--language-->
     </div> <!--language-inner-->
   </div> <!--language_detail-->
   <div class="select_lang">
     <?php $storecode = Mage::app()->getStore()->getCode(); ?>
     <img src="<?php echo $this->getSkinUrl('images/flags/'.$storecode.'.png') ?>" alt="<?php echo $storecode; ?>" /> 
     <span class="en_lang"><?php echo Mage::app()->getStore()->getName(); ?></span> 
     <span class="caret"></span>
   </div> <!--select_lang-->
 </div> <!--language-switcher-->
<script type="text/javascript">
        jQuery(function() {
                jQuery(".language-switcher").hover(function() {
                        jQuery('.select_lang').addClass('active');
                        jQuery(".language_detail").stop(true, true).slideDown(200, "easeInSine");
                        },  
                        function() {
                        jQuery('.select_lang').removeClass('active');
                        jQuery(".language_detail").stop(true, true).fadeOut(100, "easeInCubic");
                        });

        });
</script>
</div>  <!--language-box-->
<?php endif; ?>        